FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /app-produtos
COPY . /app-produtos
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app-produtos
COPY --from=build /app-produtos/target/msproduto-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8082

CMD bash -c "sleep 20 && java -jar app.jar"
