version: '3.8'
services:
  mysql_msproduto:
    image: mysql:8.0
    container_name: mysql_msproduto
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: produtosdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"      

  msproduto:
    image: aisakatfpn/msproduto:0.7
    depends_on:
      - mysql_msproduto
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_msproduto:3306/produtosdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password